### ISSUE TITLE
Conda stuck solving envirnoment during jupyter image build

### ISSUE THREAD

**Issue by tfirchau** [gorenje/sysmlv2-jupyter-docker#13]
When executing ``make spin-up`` during the build of the jupyter image, conda gets stuck solving the environment. (I aborted execution after 3:45 hours...) I observed this behaviour both natively in macOS and in WSL on Windows 10 for the current revision ([caee051](https://github.com/gorenje/sysmlv2-jupyter-docker/commit/caee0513e9995622270edf599c28d0f23aa4f88a)). This seems to be a [known problem](https://github.com/conda/conda/issues/11919).

 I fixed it for me as suggested in the coda issue by adding the following:

```
RUN ${HOME}/conda/condabin/conda update conda
RUN ${HOME}/conda/condabin/conda install -n base conda-build conda-libmamba-solver
RUN ${HOME}/conda/condabin/conda config --set solver libmamba
```

after this line:

https://github.com/gorenje/sysmlv2-jupyter-docker/blob/caee0513e9995622270edf599c28d0f23aa4f88a/Dockerfile.jupyter#L61

Solving the environment then took only a couple of minutes and the overall process completed successfully.

**Comment by gorenje** [comment]
Hi There!

Cool, thanks for the heads up and the solution 👍 

Do you want to create a PR for the street credits or are you happy for me to make the change?

I would probably get to it on the weekend ...

**Comment by tfirchau** [comment]
Initially I did not think to do a PR, but it was a nice learning / practising opportunity for me. Thank you for suggesting it!

**Comment by gorenje** [comment]
👍 

Thanks for the contribution + have a nice weekend :)
